version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - kaiser
      
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    assignees:
      - kaiser

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    assignees:
      - kaiser

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - kaiser
